# version of the docker compose
version: '3.8'

# What services are we going to use
services:
  # Frontend
  react:
    build: ./client
    container_name: tvApp_Frontend
    ports:
      - "3000:3000"
    # Allows us to see real time updates doesnt work on windows thoe
    volumes:
      - ./client:/tv_app_frontend_docker
      - /tv_app_frontend_docker/node_modules
    # Need these for it to work with react
    stdin_open: true
    tty: true
    depends_on:
      - server
      - postgres

  # Server
  server:
    build: ./server
    container_name: backend_server
    environment:
      POSTGRES_URI: postgresql://favour@postgres:5432/tvApp
    ports:
      - "5001:5001"
    volumes:
      - ./server:/tv_app_server
      - /tv_app_server/node_modules
    depends_on:
      - postgres
    
  # Postgres
  postgres:
    build: ./server/postgres
    container_name: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: favour
      POSTGRES_DB: tvApp
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5433:5432"